import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import localFont from "next/font/local";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RussoOne = localFont({
    src: [
        {
            path: "./fonts/RussoOne-Regular.ttf",
            weight: "400",
            style: "normal",

        }
    ],
    variable: "--font-russo-one",
})

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`antialiased ${RussoOne.variable}`}
            >
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
